version: "3"

services:

  tmail-backend:
    image: linagora/tmail-backend:memory-branch-master
    container_name: tmail-backend
    volumes:
      - ./tmail/jwt_publickey:/root/conf/jwt_publickey
      - ./tmail/jwt_privatekey:/root/conf/jwt_privatekey
      - ./tmail/mailetcontainer.xml:/root/conf/mailetcontainer.xml
      - ./tmail/listeners.xml:/root/conf/listeners.xml
      - ./tmail/imapserver.xml:/root/conf/imapserver.xml
      - ./tmail/jmap.properties:/root/conf/jmap.properties
      - ./tmail/linagora-ecosystem.properties:/root/conf/linagora-ecosystem.properties
      - ./tmail/openpaas.properties:/root/conf/openpaas.properties
      - ./tmail/extensions-jars/tmail-ai-bot-jar-with-dependencies.jar:/root/libs/tmail-ai-bot-jar-with-dependencies.jar
      - ./tmail/ai.properties:/root/conf/ai.properties
      - ./tmail/extensions.properties:/root/conf/extensions.properties
      - ./tmail/provisiong.sh:/root/provisioning/provisioning.sh
    ports:
        - "8002:80"
        - "8000:8000"
        - "25:25"
        - "465:465"
        - "587:587"
        - "143:143"
        - "993:993"
    environment:
      - DOMAIN=example.com
    networks:
      - tmail


networks:
  tmail:
    driver: bridge
